In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
# from sklearn.datasets import fetch_california_housing
from sklearn.datasets import fetch_openml
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [44]:
df = fetch_openml('boston' , version = 1 , as_frame = True)
df = df.frame
df.sample(5)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
125,0.16902,0.0,25.65,0,0.581,5.986,88.4,1.9929,2,188.0,19.1,385.02,14.81,21.4
84,0.05059,0.0,4.49,0,0.449,6.389,48.0,4.7794,3,247.0,18.5,396.90,9.62,23.9
247,0.19657,22.0,5.86,0,0.431,6.226,79.2,8.0555,7,330.0,19.1,376.14,10.15,20.5
463,5.82115,0.0,18.10,0,0.713,6.513,89.9,2.8016,24,666.0,20.2,393.82,10.29,20.2
236,0.52058,0.0,6.20,1,0.507,6.631,76.5,4.1480,8,307.0,17.4,388.45,9.54,25.1

In [45]:
X = df.iloc[ : , : -1]
y = df.iloc[ : , -1]

# X.head()
# y.head()

X = X.astype(float)
y = y.astype(float)

In [46]:
LR = LinearRegression()
mse = cross_val_score(LR , X , y , scoring = 'neg_mean_squared_error' , cv = 5)

mse

array([-12.46030057, -26.04862111, -33.07413798, -80.76237112,
       -33.31360656])

In [48]:
mean_mse = np.mean(mse)

mean_mse

np.float64(-37.131807467699154)

In [49]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2 , random_state = 42)

In [50]:
LR = LinearRegression()

LR.fit(X_train,y_train)

LinearRegression()

In [51]:
y_pred = LR.predict(X_test)

In [53]:
comp = pd.DataFrame({'Actual' : y_test ,
                    'Predicted' : y_pred})

comp.sample(5)

     Actual  Predicted
90     22.6  27.276186
501    22.4  24.160776
346    17.2  14.950692
381    10.9  18.765487
208    24.4  23.765790

In [59]:
r2 = metrics.r2_score(y_test,y_pred)

mae = metrics.mean_absolute_error(y_test,y_pred)

rmse = metrics.root_mean_squared_error(y_test,y_pred)

print(f'r2_score : {r2:.2f}')
print(f'mean_absolute_error : {mae:.2f}')
print(f'root_mean_squared_error : {rmse:.2f}')

r2_score : 0.67
mean_absolute_error : 3.19
root_mean_squared_error : 4.93